on:
  workflow_dispatch:
    inputs:
      message:
        description: 'Workflow message to print'
        required: true
        type: string

jobs:
  print-message:
    runs-on: ubuntu-latest
    steps:
      - name: Print the message to STDOUT
        run: echo  The Morpheus message is ${{ inputs.message }} 
      - name: Sleep for 120 seconds
        run: sleep 120s
        shell: bash
